# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 류혜수(Ryu hyesu)
title: Android Developer
email: aimee39941@gmail.com
phone: 010-2527-7223
# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  ryu-hyesu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://treeunderthehuman.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <mark>지원 동기</mark> 뚜렷한 목적과 사용자 중심의 기능 구현은 개발자로 갖추어야 할 중요한 역량이라 생각합니다. 저는 좋아하는 것을 남들에게 공유하는 걸 좋아합니다. 특히, 가사를 잘 쓰는 해외 아티스트의 곡을 한국어로 해석하여 디자인한 가사집을 친구들이나 같은 팬들에게 나누어 준 적이 있습니다. 가사집을 받은 사람들이 가사를 보고 나서 더 큰 감동을 받았다고 말해줬을 때, 뿌듯함을 느꼈으며 동시에 좋아하는 사람들에게 실질적인 도움을 주고 싶다는 동기가 생겼습니다. 
  
  최근 제가 좋아하는 아티스트의 투어가 매우 인기가 많아져 뒤늦게 티켓을 알아보는 팬들은 티켓 가격이 너무 비싸 티켓을 살 수 없었습니다. 저는 조금이라도 티켓을 싸게 사기 위해 티켓을 재판매하는 사이트의 API를 활용하여 원하는 가격 이하로 티켓이 나왔을 때 알림을 받을 수 있는 앱을 만들었습니다. 그리고 사용자의 필요를 이해하고 그에 맞는 기능을 구현하는 과정은 매우 의미 있었습니다. 

  저의 사용자 중심의 경험으로 얻은 귀사에 도움이 될 수 있도록 최선을 다하겠습니다.

  <mark>성격 장단점</mark> 저는 도움이 필요한 사람에게 도움을 주는 것을 좋아합니다. 대학 시절 개발 동아리에서 첫 프로젝트를 진행했을 때, 팀원들에게 필요한 일이 없는지 자주 물어보곤 했습니다. 그 덕분에 도움을 받은 팀원도 있었고, 저 또한 팀에게 도움이 된다는 사실에 보람을 느끼며 자연스럽게 팀장 역할을 맡게 되었습니다. 

  하지만 프로젝트의 마감 기한이 다가오며 팀원에게 도움을 넘어 간섭을 하는 경우가 있었습니다. 제 방식에 불만이 생긴 팀원과 갈등을 겪게 되었고, 차분히 돌아보니 제가 팀원의 작업 방식을 충분히 존중하지 않고 조언을 했음을 깨달았습니다.

  이 경험을 통해 상대방에 대한 존중과 배려의 태도를 갖추었을 때, 돕고자 하는 마음이 정확하게 전달될 수 있다는 것을 배웠습니다. 이후 다른 프로젝트에서 이런 깨달음을 갖고 팀원들과 커뮤니케이션을 더욱 원활하게 진행할 수 있었습니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 간호사 일상 및 건강 실태 조사 어플 제작
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Android Developer
        caption: 2024. 01 - 2024. 07 (7개월)
        quote: >
          중앙대학교 대학원의 연구 프로젝트로, 간호사 일상 및 건강 설문조사 애플리케이션 개발 외주를 받았습니다.
        description: | # this will include new lines to allow paragraphs
            Android Studio와 Kotlin을 사용하여 서비스 프론트엔드를 개발하고, Firebase를 활용해 14일간 간호사들의 일일 근무 생활과 건강 척도 데이터를 수집하는 시스템을 구축했습니다.
            
            프로젝트 진행 중 클라이언트의 요구사항을 충족시키면서도 앱의 성능 개선이 필요하다는 점을 동료들과의 코드 리뷰를 통해 인식했습니다. 이 문제를 해결하기 위해 코루틴 도입을 제안했고, 관련 서적과 공식 문서를 공부하여 효과적으로 구현했습니다. 그 결과, 앱의 반응 속도를 크게 향상시킬 수 있었습니다. 또한, 개발 프로세스의 효율성 향상에도 관심을 가져 배포 자동화에 대해 공부했습니다. 현직자 강연을 찾아 학습한 후, GitHub Actions를 활용한 자동화 시스템을 구축하여 배포 시간을 대폭 단축시켰습니다.
            
            이러한 경험들을 통해 제 기술적 역량이 향상되었으며, 동시에 지속적인 학습과 팀원과의 소통의 중요성을 깊이 깨달았습니다.

      - layout: left
        title: 멘토르7 스터디카페
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 카페 매니저
        caption: 2021. 02 - 2024. 06 (3 년 6 개월)
        quote: >
          가족 운영 스터디카페의 개업 초기부터 매니저로 참여했습니다.
        description: | # this will include new lines to allow paragraphs
            각종 민원 처리, 시설 및 비품 구비, 가게 세부 인테리어 참여 등 대처 메뉴얼이 없고, 모든 것을 새롭게 시작해야 했기 때문에 가게 운영 체계를 마련하는 데에 적극적으로 참여하였습니다.
            
            하지만 외부에서 소음이 발생하거나 카페 수도관이 터져 바닥이 물 바다가 되는 등 돌발 상황에 대처할 수 있는 매뉴얼이 없었습니다. 처음에는 단순히 민원에 답변하는 것으로 그쳤는데, 사전 공지가 없었다며 관리가 미흡하다는 내용의 부정적인 후기가 몇 개 올라왔습니다. 
            
            이 후 상의를 통해  돌발 상황 발생 시 이용자들에게 개별적으로 말씀드리거나 단체 문자를 보내 상황을 신속히 알리고, 이용 시간을 추가하거나 환불 해드리는 등의 보상 조치를 취했습니다. 이후 더 심각한 소음이 며칠 간 지속되었을 때에도 이전과 같은 부정적인 후기는 거의 발생하지 않았습니다. 

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Nurse Health Survey
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)

        quote: >
          중앙대학원의 간호사 대상 일상 및 건강 조사를 위한 2주간 데이터 수집 안드로이드 애플리케이션 개발
        description: | # this will include new lines to allow paragraphs
          - Google 로그인 API와 Firebase Authentication을 활용한 사용자 인증 구현
          - Firebase Realtime Database와 Room Database를 이용한 클라우드 및 로컬 데이터 관리
          - Fragment와 Navigation Component를 활용한 UI/UX 설계 및 구현
          - JSON 파싱 및 RecyclerView를 활용한 동적 설문조사 페이지 개발
          - Firebase Cloud Messaging을 이용한 알림 시스템 구축
          - GitHub Actions를 통한 CI/CD 파이프라인 구축 및 Google Play Console을 통한 앱 출시

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: IS IT OVER NOW?
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          실시간 공연 정보 및 티켓 가격 모니터링 어플리케이션
        description: | # this will include new lines to allow paragraphs
          - Retrofit2를 활용한 Ticketmaster Open API 연동 및 실시간 공연 정보 조회 구현
          - Google Maps API를 이용한 공연 위치 시각화 및 커스텀 InfoWindow 개발
          - WorkManager를 활용한 주기적 백그라운드 작업으로 자동화된 티켓 가격 모니터링 시스템 구축
          - Room 데이터베이스를 이용한 로컬 데이터 관리 및 사용자 맞춤 기능 구현
          - RESTful API 통신, 데이터 파싱, 커스텀 어댑터 개발을 통한 효율적인 데이터 처리 및 표시

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 수강신청 모의 사이트
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/ddwu-aws-cloud-club/team-b.git

        quote: >
          대규모 수강 신청을 시뮬레이션하는 백엔드 및 인프라 프로젝트
        description: | # this will include new lines to allow paragraphs
          - Spring Boot를 활용한 학생 정보 CRUD 및 수강 과목 조회 API 개발
          - Prometheus, Grafana, Alertmanager를 이용한 실시간 모니터링 시스템 구축
          - Slack 연동을 통한 자동화된 알림 시스템 구현
          - Apache Bench를 사용한 대규모 부하 테스트(15,000명/15,000회 요청) 수행 및 성능 분석

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 산타와 선물 대소동
        link: https://store.steampowered.com/app/2244410/Santa_and_present_chaos/
        link_text: 스팀 상점 페이지 링크

        quote: >
          크리스마스 전날 선물을 되찾기 위한 소년 산타의 동화 속 모험을 떠나는 게임
        description: | # this will include new lines to allow paragraphs
          - 전체 기획 및 대사 스크립트 작성
          - <mark>JSON</mark>을 활용한 세이브 시스템 구축
          - 동적 카메라 시스템 및 카메라 워크 구현
          - <mark>Ink 라이브러리</mark> 기반 대화 시스템 및 연동 애니메이션 제작

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 동덕 여자 대학교
        caption: 2020. 03 - 2024. 08
        quote: >
          컴퓨터학과 본 전공, 정보통계학과 복수 전공했으며 졸업 예정입니다.

  - title: Presentation
    layout: text
    content: | # this will include new lines to allow paragraphs
      포트폴리오
      - [포트폴리오 바로가기](https://glowing-barber-b5f.notion.site/c38a027bbce84433b3b391c9acf4647b?pvs=4)
      
      발표 자료
      - [yolo ver.1 논문 구현 발표](https://speakerdeck.com/skdfjwa/yolo-ver-dot-1-nonmun-guhyeon)
      - [AWS VPC 발표](https://speakerdeck.com/skdfjwa/aws-vpc-balpyo)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
